### ISSUE TITLE
hello, how to get frames?

### ISSUE THREAD

**Issue by yeyuchen198** [obfio/twitter-tid-generator#3]
hello, how to get frames?

frames [][][]int

but I got Two-dimensional array
 with JS code:
 wo = (n,t)=>vo = vo || To(Do(So(n))[t[5] % 4][eo(0, 0, 0, "zfS8", 1310) + tW("b7EK", 130, 69, 66, 86)][0][Eo(55, -142, "GGQA", -62, -59) + tW("6#2E", 113, 25, 67, 116)][1], "d")[eo(0, 0, 0, "6ULc", 1185) + Eo(-40, -164, "j$D%", -44, -96)](9)[tW("$oro", 92, 47, -5, -120)]("C")[Eo(209, 214, "XX#j", 81, 136)]((n=>n[Jo(0, 0, 0, 771, "r0p%") + "ce"](/[^\d]+/g, " ")[Jo(0, 0, 0, 754, "jGSw")]()[Eo(108, 51, "51Mb", 74, 71)](" ")[lo("dn@4", 1153)](so)))

for example:
[[80,230,213,41,95,224,104,253,152,230,117],[161,244,148,112,148,220,171,194,32,119,170],[111,252,148,124,42,163,190,176,241,211,234],[173,221,202,60,165,213,91,18,225,62,142],[28,105,115,76,27,239,79,54,194,198,35],[37,215,100,97,39,174,6,226,239,235,63],[214,52,241,47,148,120,9,130,142,4,229],[116,233,87,104,58,93,0,152,72,164,203],[232,28,1,136,176,178,206,47,231,198,165],[191,236,47,32,228,18,181,200,51,187,27],[136,199,96,148,20,147,92,38,199,221,133],[204,182,172,24,185,69,56,60,88,245,138],[72,236,115,13,29,202,111,72,212,157,103],[112,86,68,252,121,158,49,4,208,88,8],[185,172,224,218,232,9,186,71,155,35,193],[13,191,52,99,160,76,106,92,102,233,177]]

**Comment by yeyuchen198** [comment]
The generated value is 115 bits long? Actually should get 94 bits

**Comment by yeyuchen198** [comment]
> The generated value is 115 bits long? Actually should get 94 bits

yes, 94 is correct
n = document.querySelectorAll("[name^=tw]")[0].getAttribute("content"), new Uint8Array(atob(n)["split"]("")["map"](n => n["charCodeAt"](0)))

get 48 bits

**Comment by EvilisZero** [comment]
hello, did you manage to know how to get the frames?

**Comment by animencoding** [comment]
@EvilisZero have you managed to figure this out?

**Comment by obfio** [comment]
This should explain it: https://antibot.blog/twitter-header-part2/, https://antibot.blog/twitter-header-part-3/
